/* Generated By:JavaCC: Do not edit this line. ParserTreeConstants.java Version 5.0 */
package org.nfunk.jep;

public interface ParserTreeConstants
{
  public int JJTSTART = 0;
  public int JJTVOID = 1;
  public int JJTFUNNODE = 2;
  public int JJTVARNODE = 3;
  public int JJTCONSTANT = 4;


  public String[] jjtNodeName = {
    "Start",
    "void",
    "FunNode",
    "VarNode",
    "Constant",
  };
}
/* JavaCC - OriginalChecksum=fe7acd08fba6f68e37315360cc6d94d2 (do not edit this line) */
