/* Generated By:JJTree&JavaCC: Do not edit this line. ParserConstants.java */
package org.nfunk.jep;

public interface ParserConstants {

  int EOF = 0;
  int INTEGER_LITERAL = 7;
  int DECIMAL_LITERAL = 8;
  int STRING_LITERAL = 9;
  int DEFAULT_FP_LITERAL = 10;
  int DEF_EXPONENT = 11;
  int DEFAULT_DEC_SEPARATOR = 12;
  int ALT_FP_LITERAL = 13;
  int ALT_EXPONENT = 14;
  int ALT_DEC_SEPARATOR = 15;
  int INDENTIFIER1 = 16;
  int LETTER1 = 17;
  int DIGIT1 = 18;
  int INDENTIFIER2 = 19;
  int LETTER2 = 20;
  int DIGIT2 = 21;
  int ASSIGN = 22;
  int SEMI = 23;
  int COMMA = 24;
  int GT = 25;
  int LT = 26;
  int EQ = 27;
  int LE = 28;
  int GE = 29;
  int NE = 30;
  int AND = 31;
  int OR = 32;
  int PLUS = 33;
  int MINUS = 34;
  int MUL = 35;
  int DOT = 36;
  int DIV = 37;
  int MOD = 38;
  int NOT = 39;
  int POWER = 40;
  int CROSS = 41;
  int LSQ = 42;
  int RSQ = 43;
  int LRND = 44;
  int RRND = 45;
  int COLON = 46;

  int ALT_SEPARATORS = 0;
  int NO_DOT_IN_IDENTIFIERS = 1;
  int DEFAULT = 2;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "<token of kind 5>",
    "<token of kind 6>",
    "<INTEGER_LITERAL>",
    "<DECIMAL_LITERAL>",
    "<STRING_LITERAL>",
    "<DEFAULT_FP_LITERAL>",
    "<DEF_EXPONENT>",
    "<DEFAULT_DEC_SEPARATOR>",
    "<ALT_FP_LITERAL>",
    "<ALT_EXPONENT>",
    "<ALT_DEC_SEPARATOR>",
    "<INDENTIFIER1>",
    "<LETTER1>",
    "<DIGIT1>",
    "<INDENTIFIER2>",
    "<LETTER2>",
    "<DIGIT2>",
    "\"=\"",
    "\";\"",
    "\",\"",
    "\">\"",
    "\"<\"",
    "\"==\"",
    "\"<=\"",
    "\">=\"",
    "\"!=\"",
    "\"&&\"",
    "\"||\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\".\"",
    "\"/\"",
    "\"%\"",
    "\"!\"",
    "\"^\"",
    "\"^^\"",
    "\"[\"",
    "\"]\"",
    "\"(\"",
    "\")\"",
    "\":\"",
  };

}
