/* Generated By:JavaCC: Do not edit this line. ParserVisitor.java Version 5.0 */
package org.nfunk.jep;

public interface ParserVisitor
{
  public Object visit(SimpleNode node, Object data) throws ParseException;
  public Object visit(ASTStart node, Object data) throws ParseException;
  public Object visit(ASTFunNode node, Object data) throws ParseException;
  public Object visit(ASTVarNode node, Object data) throws ParseException;
  public Object visit(ASTConstant node, Object data) throws ParseException;
}
/* JavaCC - OriginalChecksum=9ad1cc1117ef6c5bfb29a37107f9a915 (do not edit this line) */
